<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Posisi extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Tbl_posisi_model');
        $this->load->library('form_validation');        
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','posisi/tbl_posisi_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Tbl_posisi_model->json();
    }

    public function read($id) 
    {
        $row = $this->Tbl_posisi_model->get_by_id($id);
        if ($row) {
            $data = array(
		'id_posisi' => $row->id_posisi,
		'kd_posisi' => $row->kd_posisi,
		'nama_posisi' => $row->nama_posisi,
		'keterangan' => $row->keterangan,
	    );
            $this->template->load('template','posisi/tbl_posisi_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('posisi'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('posisi/create_action'),
	    'id_posisi' => set_value('id_posisi'),
	    'kd_posisi' => set_value('kd_posisi'),
	    'nama_posisi' => set_value('nama_posisi'),
	    'keterangan' => set_value('keterangan'),
	);
        $this->template->load('template','posisi/tbl_posisi_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
		'kd_posisi' => $this->input->post('kd_posisi',TRUE),
		'nama_posisi' => $this->input->post('nama_posisi',TRUE),
		'keterangan' => $this->input->post('keterangan',TRUE),
	    );

            $this->Tbl_posisi_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('posisi'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Tbl_posisi_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('posisi/update_action'),
		'id_posisi' => set_value('id_posisi', $row->id_posisi),
		'kd_posisi' => set_value('kd_posisi', $row->kd_posisi),
		'nama_posisi' => set_value('nama_posisi', $row->nama_posisi),
		'keterangan' => set_value('keterangan', $row->keterangan),
	    );
            $this->template->load('template','posisi/tbl_posisi_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('posisi'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id_posisi', TRUE));
        } else {
            $data = array(
		'kd_posisi' => $this->input->post('kd_posisi',TRUE),
		'nama_posisi' => $this->input->post('nama_posisi',TRUE),
		'keterangan' => $this->input->post('keterangan',TRUE),
	    );

            $this->Tbl_posisi_model->update($this->input->post('id_posisi', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('posisi'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Tbl_posisi_model->get_by_id($id);

        if ($row) {
            $this->Tbl_posisi_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('posisi'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('posisi'));
        }
    }

    public function _rules() 
    {
	$this->form_validation->set_rules('kd_posisi', 'kd posisi', 'trim|required');
	$this->form_validation->set_rules('nama_posisi', 'nama posisi', 'trim|required');
	$this->form_validation->set_rules('keterangan', 'keterangan', 'trim|required');

	$this->form_validation->set_rules('id_posisi', 'id_posisi', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Posisi.php */
/* Location: ./application/controllers/Posisi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-01 19:56:57 */
/* http://harviacode.com */