<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Tbl_asetkantor_model extends CI_Model
{

    public $table = 'tbl_asetkantor';
    public $id = 'id_aset';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_aset,kd_jenis,kd_AKantor,nm_Akantor,merk,asal,tahun,jumlah,satuan,ukuran,status,kondisi,harga,spek_lain,ket');
        $this->datatables->from('tbl_asetkantor');
        //add this line for join
        //$this->datatables->join('table2', 'tbl_asetkantor.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('asetkantor/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('asetkantor/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('asetkantor/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_aset');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_aset', $q);
	$this->db->or_like('kd_jenis', $q);
	$this->db->or_like('kd_AKantor', $q);
	$this->db->or_like('nm_Akantor', $q);
	$this->db->or_like('merk', $q);
	$this->db->or_like('asal', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('ukuran', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('kondisi', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('spek_lain', $q);
	$this->db->or_like('ket', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_aset', $q);
	$this->db->or_like('kd_jenis', $q);
	$this->db->or_like('kd_AKantor', $q);
	$this->db->or_like('nm_Akantor', $q);
	$this->db->or_like('merk', $q);
	$this->db->or_like('asal', $q);
	$this->db->or_like('tahun', $q);
	$this->db->or_like('jumlah', $q);
	$this->db->or_like('satuan', $q);
	$this->db->or_like('ukuran', $q);
	$this->db->or_like('status', $q);
	$this->db->or_like('kondisi', $q);
	$this->db->or_like('harga', $q);
	$this->db->or_like('spek_lain', $q);
	$this->db->or_like('ket', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Tbl_asetkantor_model.php */
/* Location: ./application/models/Tbl_asetkantor_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-11-01 21:09:54 */
/* http://harviacode.com */